---
- name: install cerebro
  include_role:
    name: utils
    tasks_from: install-pkg
  vars:
    version: 0.8.5
    parentRole: cerebro
  loop:
  - pkgUrl: "https://github.com/lmenezes/cerebro/releases/download/v{{ version }}/cerebro-{{ version }}.tgz"
  loop_control:
    loop_var: opts

- name: install service
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
  - lib/systemd/system/
  loop_control:
    loop_var: file_path

- name: copy bin files
  copy:
  copy:
    src: "{{ role_path }}/files/{{ file_path }}"
    dest: /{{ file_path }}
    owner: root
    group: cerebro
  loop:
  - opt/app/conf/
  - opt/cerebro/current/conf/
  loop_control:
    loop_var: file_path

- name: mask service
  systemd:
    name: cerebro
    enabled: no
    masked: yes
    state: stopped
