---
- name: set up default svc home var
  set_fact:
    defaultSvcHome: "/opt/{{ parentRole }}/{{ opts.version | default(version) }}"

- name: set up variables
  set_fact:
    pkgType: "{{ opts.pkgType | default('tgz') }}"
    extraOpts: "{{ opts.extractArgs | default([ '--strip-components=1' ]) }}"
    svcHome: "{{ opts.svcHome | default(defaultSvcHome) }}"
    svcVersion: "{{ opts.version | default(version) }}"
    creates: "{{ opts.creates | default('bin') }}"
    softLink: "{{ opts.softLink | default(true) }}"

- name: install tools
  apt:
    name: ['unzip']
    state: present
    update_cache: no
  when: pkgType == 'zip'

- name: prepare service group
  group:
    name: svc
    state: present

- name: Add the Service User - {{ parentRole }}
  user:
    name: "{{ parentRole }}"
    groups: svc
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

- name: Prepare service directories - {{ parentRole }}
  file:
    path: "{{ svcHome }}"
    owner: "{{ parentRole }}"
    group: svc
    state: directory

- name: check if package file exists
  stat:
    path: "{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp/{{ parentRole }}-{{ svcVersion }}.{{ pkgType }}"
  register: pkg_file
  run_once: True
  delegate_to: localhost

- name: prepare local dir
  file:
    dest: "{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp"
    state: directory
  delegate_to: localhost

- name: Download service package - {{ parentRole }}
  get_url:
    url: "{{ opts.pkgUrl }}"
    dest: "{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp/{{ parentRole }}-{{ svcVersion }}.{{ pkgType }}"
  delegate_to: localhost
  run_once: True
  when:
  - opts.pkgUrl is defined
  - pkg_file.stat.exists == False

- name: Extract binary - {{ parentRole }}
  unarchive:
    src: "{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp/{{ parentRole }}-{{ svcVersion }}.{{ pkgType }}"
    dest: "{{ svcHome }}"
    creates: "{{ svcHome }}/{{ creates }}"
    extra_opts: "{{ extraOpts }}"
    owner: "{{ parentRole }}"
    group: svc

- name: set permissions - {{ parentRole }}
  file:
    path: "{{ svcHome }}"
    owner: "{{ parentRole }}"
    group: svc
    recurse: yes

- name: create symbolic link - {{ parentRole }}
  file:
    src: "{{ svcVersion }}"
    dest: "/opt/{{ parentRole }}/current"
    owner: "{{ parentRole }}"
    group: svc
    state: link
  when:
  - svcHome == defaultSvcHome and softLink
