---
- name: Compile tmpl files
  shell: |
    compileTmpls() {
      local srcFiles=${@:2} destFile=$1
      for tmpl in $srcFiles; do
        (cat $tmpl; echo) >> $destFile
      done
    }

    srcDir="{{ playbook_dir }}/roles/{{ role_name }}/files/etc/confd/templates/make.sh"
    srcFiles="$(ls $srcDir/*.tmpl)"

    destDir="{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp/confd/templates"
    rm -rf $destDir && mkdir -p $destDir

    compileTmpls $destDir/make.sh.tmpl $srcFiles

    extraSrcDir="{{ playbook_dir }}/roles/{{ parentRole }}/files/etc/confd/templates"
    [ -d "$extraSrcDir" ] && for srcDir in $(ls -d {{ playbook_dir }}/roles/{{ parentRole }}/files/etc/confd/templates/*); do
      compileTmpls $destDir/$(basename $srcDir).tmpl $(ls $srcDir/*)
    done
  args:
    executable: /bin/bash
  delegate_to: localhost

- name: Copy confd files
  copy:
    src: "{{ path.src }}/"
    dest: /etc/confd/{{ path.dest }}/
    owner: root
    group: root
  loop:
  - src: "{{ playbook_dir }}/roles/{{ role_name }}/files/etc/confd/conf.d"
    dest: conf.d
  - src: "{{ playbook_dir }}/roles/{{ parentRole }}/files/etc/confd/conf.d"
    dest: conf.d
  - src: "{{ playbook_dir }}/roles/{{ parentRole }}/files/tmp/confd/templates"
    dest: templates
  loop_control:
    loop_var: path
  when: path.src is directory
